### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by hbetts** [singapore/gl-got#28]
@rarkins would you please publish version 7.0.0 to the npm registry?

I've merged in `gh-got` commits into `gl-got`.

Also, #26 can be closed as that update was one of the commits I pulled from `gh-got`.

**Comment by rarkins** [comment]
@hbetts done. I added you as a collaborator for this package on npmjs.com too

**Comment by hbetts** [comment]
Thank you @rarkins! :smile:
