### ISSUE TITLE
Unpin dependencies?

### ISSUE THREAD

**Issue by rarkins** [singapore/gl-got#32]
Because this is a library that is consumed by others, should we "unpin" its dependencies and revert to ranges? And if so, then which ranges? And keep devDependencies pinned or also ranges?

**Comment by hbetts** [comment]
@rarkins the dependencies are unpinned, which I think is correct.

Personally, pinning dev dependencies doesn't make sense to me, but that seems to be inline with the default behavior of `renovate`'s _library_ configuration.

What I would like to do is remove the `renovate` configuration from `package.json` and let `renovate`, the service, submit a pull request to update the project to use the _library_ configuration. That way we're dog fooding the standard Renovate setup.

**Comment by hbetts** [comment]
I removed Renovate configuration in 1fd3a73dc497ee97d6304869783f0a13ed914cf1

Now I guess I just need to wait 30 minutes for Renovate to submit a configuration pull request.

**Comment by rarkins** [comment]
@hbetts actually it also needed the existing "Configure Renovate" PR renamed to something else in order to trick Renovate into creating a new one. Due to legacy reasons, a repo is considered "onboarded" if either it contains a `renovate.json` or has a closed Configure Renovate PR, i.e. allowing people to skip adding an extra file to the repo if they choose to trust the defaults.

**Comment by rarkins** [comment]
FYI, I have also moved to using `config:base` as my default preset rather than `:library`. 

Before:
- If all package.json files in the repo are private then set to `:app`, else set to `:library`

Now:
- Autodetect app vs library each run and each package.json, i.e. private ones or ones missing a `main` will pin dependencies while all others get old `:library` treatment
- Users can manually override pinning or not pinning of course
